version: '3'

services:
  postgres:
    image: postgres:16.1
    container_name: postgresdb_playground
    environment:
      POSTGRES_USER: "local"
      POSTGRES_PASSWORD: "1234"
      POSTGRES_DB: "playground"
    ports:
      - "5432:5432"
    volumes:
      - postgres_db:/var/lib/postgresql/data

volumes:
  postgres_db:
